spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/testdb
mybatis-plus:
  mapper-locations: classpath:./mapper/**/*.xml
  config-location: classpath:./mybatis-config.xml
